<a href="https://colab.research.google.com/github/Jakemeister7/Data-Analysis-With-Python-Course/blob/main/Pandas_9_Functions_and_Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas - Functions and Sorting

In [356]:
import pandas as pd
import numpy as np

In [357]:
# Create Dataframe
stuff = {
    'Corporation':["Apple", "Google", "Meta", "Apple", "Google", "Meta"],
    'Employees':['John', 'April', 'Wes', 'Aspen', 'Beth', 'Steph'],
    'Salary':[200, 220, 190, 130, 120, 150]}
my_df = pd.DataFrame(stuff)
my_df

  Corporation Employees  Salary
0       Apple      John     200
1      Google     April     220
2        Meta       Wes     190
3       Apple     Aspen     130
4      Google      Beth     120
5        Meta     Steph     150

In [358]:
# Create Function to change $ to thousands
def times1000(x):
  return x * 1000

In [359]:
# Apply the function
my_df['Salary'].apply(times1000)

0    200000
1    220000
2    190000
3    130000
4    120000
5    150000
Name: Salary, dtype: int64

In [360]:
# Format it nicer with decimals
def times1000(x):
  return format(x * 1000, ",d")

In [361]:
my_df['Salary'].apply(times1000)

0    200,000
1    220,000
2    190,000
3    130,000
4    120,000
5    150,000
Name: Salary, dtype: object

In [362]:
# Make it into a dataframe
pd.DataFrame(my_df['Salary'].apply(times1000))

    Salary
0  200,000
1  220,000
2  190,000
3  130,000
4  120,000
5  150,000

In [363]:
# Add the new data to the old dataframe
my_df["Salary"] = my_df['Salary'].apply(times1000)
my_df

  Corporation Employees   Salary
0       Apple      John  200,000
1      Google     April  220,000
2        Meta       Wes  190,000
3       Apple     Aspen  130,000
4      Google      Beth  120,000
5        Meta     Steph  150,000

In [364]:
# Add last name to names
def namer(x):
  if x == "John":
    return "John Elder"
  elif x == "April":
    return "April Elder"
  else:
    return x

In [365]:
# Apply it
my_df["Employees"].apply(namer)

0     John Elder
1    April Elder
2            Wes
3          Aspen
4           Beth
5          Steph
Name: Employees, dtype: object

In [383]:
# Use Lambdas inline
my_df['Salary'].apply(lambda x: format(int(x.replace(',', '')) * 1000, ',d'))

0    200,000,000,000
1    220,000,000,000
2    190,000,000,000
3    130,000,000,000
4    120,000,000,000
5    150,000,000,000
Name: Salary, dtype: object

In [384]:
# Make dataframe
pd.DataFrame(my_df["Salary"].apply(lambda x: format(int(x.replace(',', '')) * 1000, ',d')))

            Salary
0  200,000,000,000
1  220,000,000,000
2  190,000,000,000
3  130,000,000,000
4  120,000,000,000
5  150,000,000,000

In [385]:
# Append that stuff back to original dataframe
my_df['Salary'] = my_df['Salary'].apply(lambda x: format(int(x.replace(',', '')) * 1000, ',d'))
my_df

  Corporation Employees           Salary
0       Apple      John  200,000,000,000
1      Google     April  220,000,000,000
2        Meta       Wes  190,000,000,000
3       Apple     Aspen  130,000,000,000
4      Google      Beth  120,000,000,000
5        Meta     Steph  150,000,000,000

In [369]:
# Apply Functions to multiple columns (corp and emps)
def names(x):
  return f'Codemy: {x}'

In [370]:
# Apply To Two Columns
my_df[["Corporation", "Employees"]].apply(names)

Corporation    Codemy: 0     Apple\n1    Google\n2      Meta\...
Employees      Codemy: 0     John\n1    April\n2      Wes\n3 ...
dtype: object

In [386]:
# Append to Current DataFrame
pd.DataFrame(my_df[["Corporation", "Employees"]].apply(names))

                                                             0
Corporation  Codemy: 0     Apple\n1    Google\n2      Meta\...
Employees    Codemy: 0     John\n1    April\n2      Wes\n3 ...

In [387]:
# Sort Salaries from lowest to highest
my_df

  Corporation Employees           Salary
0       Apple      John  200,000,000,000
1      Google     April  220,000,000,000
2        Meta       Wes  190,000,000,000
3       Apple     Aspen  130,000,000,000
4      Google      Beth  120,000,000,000
5        Meta     Steph  150,000,000,000

In [388]:
# Sort Salaries from Highest to Lowest Descending
my_df.sort_values('Salary', ascending=False, inplace=True)

  Corporation Employees           Salary
1      Google     April  220,000,000,000
0       Apple      John  200,000,000,000
2        Meta       Wes  190,000,000,000
5        Meta     Steph  150,000,000,000
3       Apple     Aspen  130,000,000,000
4      Google      Beth  120,000,000,000

In [391]:
# Not Permanent without inplace=True
my_df

  Corporation Employees           Salary
1      Google     April  220,000,000,000
0       Apple      John  200,000,000,000
2        Meta       Wes  190,000,000,000
5        Meta     Steph  150,000,000,000
3       Apple     Aspen  130,000,000,000
4      Google      Beth  120,000,000,000

In [396]:
# Sort Strings Alphabetically Ascending A to Z
my_df.sort_values('Corporation', inplace=True)
my_df

  Corporation Employees           Salary
0       Apple      John  200,000,000,000
3       Apple     Aspen  130,000,000,000
4      Google      Beth  120,000,000,000
1      Google     April  220,000,000,000
2        Meta       Wes  190,000,000,000
5        Meta     Steph  150,000,000,000

In [395]:
# Sort Strings Alphabetically Descending Z to A
my_df.sort_values("Corporation", ascending=False)
my_df

  Corporation Employees           Salary
2        Meta       Wes  190,000,000,000
5        Meta     Steph  150,000,000,000
0       Apple      John  200,000,000,000
4      Google      Beth  120,000,000,000
3       Apple     Aspen  130,000,000,000
1      Google     April  220,000,000,000